/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import mycode.dbconnect;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Acer
 */
public class ad extends javax.swing.JPanel {

    /**
     * Creates new form ad
     * 
     * 
     */
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs =null;
    
    
    
    public ad() {
        initComponents();
        jPanel1.setBackground(new Color(255,255,255,220));
       
        con =dbconnect.connect();
        tableload();
        jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,24));
        jTable1.getTableHeader().setOpaque(false);
       
        jTable1.getTableHeader().setBackground(new Color(255,51,51));
        jTable1.getTableHeader().setForeground( Color.BLACK);
        jTable1.setRowHeight(25);
            
    }
    public void tableload()
    {
       try{
      
         String sql = "SELECT  unit as 'Bar code', product_name as 'Description' ,unit_price as '1kg or 1pac sell price', ub_price as '1kg or 1pac buy price' , quantity as 'Grand quantity' ,profit as 'Profit Rate' FROM addsave1" ;
         pst=con.prepareStatement(sql);
         rs=pst.executeQuery();
         
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
               
       }catch(Exception e){
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pname1 = new javax.swing.JTextField();
        uprice = new javax.swing.JTextField();
        sqty = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        ubprice = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1917, 828));
        setPreferredSize(new java.awt.Dimension(1917, 828));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setText("id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 80, 50));

        jButton2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/update.jpg"))); // NOI18N
        jButton2.setText("update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, 160, 50));

        jButton1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/ok_100483.jpg"))); // NOI18N
        jButton1.setText("add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 730, 160, 50));

        jButton3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/cancel_100824.jpg"))); // NOI18N
        jButton3.setText("delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 730, 160, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Search.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, 50));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setText("product id        :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, 44));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setText("stock qty          :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, -1, 44));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setText("unit bye price  :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 44));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/addnew.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 40, 44));

        pname1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        pname1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        pname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pname1ActionPerformed(evt);
            }
        });
        pname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pname1KeyPressed(evt);
            }
        });
        jPanel1.add(pname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 470, 44));

        uprice.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        uprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        uprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                upriceKeyPressed(evt);
            }
        });
        jPanel1.add(uprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 470, 44));

        sqty.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        sqty.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(sqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 200, 44));

        jTextField4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jTextField4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 400, 40));

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel6.setText("product name  :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 44));

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bar code", "Description", "Price", "Quantity", "Title 5", "Title 6"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 1220, 830));

        jLabel7.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel7.setText("unit sell price :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 180, 44));

        ubprice.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        ubprice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        ubprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubpriceKeyPressed(evt);
            }
        });
        jPanel1.add(ubprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 470, 44));

        jTextField1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 590, 210, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 830));
        jPanel1.getAccessibleContext().setAccessibleName("");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Desktop\\1844418.jpg")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 830));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        String name = pname1.getText();
       // String price =uprice.getText();
     //String qty = sqty.getText();
        Double price2=Double.valueOf(ubprice.getText());
        String bprice=String.format("%.2f", price2);
        
        Double price=Double.valueOf(uprice.getText());
        String price1=String.format("%.2f", price);
        
        Double qty=Double.valueOf(sqty.getText());
        Double qty2=Double.valueOf(jTextField1.getText());
        Double tot_qty;
        tot_qty=(Double)qty+qty2;
        String qty1=String.format("%.2f", tot_qty);
        
        Double profit;
        profit = price-price2;
        Double profit2;
        profit2 = (profit/price)*100.00;
        long profit3;
            profit3 = Math.round(profit2);
        
        String profitt=String.format("%.2f%%", profit2);
       
        
        try{
        
       String q= "INSERT INTO addsave1(product_name,unit_price,ub_price,quantity,profit) values ('"+name+"' , '"+price1+"' , '"+bprice+"'  , '"+qty1+"' ,'"+profitt+"' )"; 
       pst = con.prepareStatement(q);
       pst.execute();
       
       tableload();
        }
        catch(Exception e){
          System.out.println(e);
          
      }
        pname1.setText("  ");
        ubprice.setText("  ");
        uprice.setText("  ");
        sqty.setText("   ");
    }//GEN-LAST:event_jButton1ActionPerformed
        
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      
           int r = jTable1.getSelectedRow();
        String uit = jTable1.getValueAt(r, 0).toString();
        String name = jTable1.getValueAt(r, 1).toString();
        String bprice = jTable1.getValueAt(r, 2).toString();
        String price = jTable1.getValueAt(r, 3).toString();
        String qty = jTable1.getValueAt(r, 4).toString();
        jLabel5.setText(uit);
        pname1.setText(name);
        ubprice.setText(price);
        uprice.setText(bprice);
        sqty.setText(qty);                 
       
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        int x = JOptionPane.showConfirmDialog(null, "Do You Really Want To Update");
        if(x==0)
    {
      String id = jLabel5.getText();
      String name = pname1.getText();
     // String price = uprice.getText();
      //double price = Double.parseDouble(uprice.getText());
       Double price2=Double.valueOf(ubprice.getText());
        String bprice=String.format("%.2f", price2);
      
       Double price=Double.valueOf(uprice.getText());
        String price1=String.format("%.2f", price);
      
     // String qty = sqty.getText();
       // double qty = Double.parseDouble(sqty.getText());
       Double qty=Double.valueOf(sqty.getText());
        Double qty2=Double.valueOf(jTextField1.getText());
        Double tot_qty;
        tot_qty=(Double)qty+qty2;
        String qty1=String.format("%.2f", qty);
        
        Double profit;
        profit = price-price2;
        Double profit2;
        profit2 = (profit/price)*100.00;
            long profit3;
            profit3 = Math.round(profit2);
        String profitt=String.format("%.2f%%", profit2);
        
        
      
      String sql = " UPDATE addsave1 SET product_name = '"+ name +"' ,unit_price = '"+ price1 +"' , ub_price = '"+bprice+"'  ,quantity = '"+ qty1 +"' , profit = '"+profitt+"'  where unit ='"+ id +"'";   
        try{
            
         pst = con.prepareStatement(sql);
         pst.execute(); 
         
         tableload();
            
        }catch(Exception e){
    }//GEN-LAST:event_jButton2ActionPerformed
    }
        pname1.setText("  ");
        ubprice.setText("  ");
        uprice.setText("  ");
        sqty.setText("   ");  
        
        
    }
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int x = JOptionPane.showConfirmDialog(null,"Do You Really Want To Delete");
        if(x==0)
        {
        
        String id = jLabel5.getText();
        
        String sql = "DELETE from addsave1 where unit='"+id+"' ";
        try {
        
         pst = con.prepareStatement(sql);
         pst.execute();
            
           tableload(); 
            
    }//GEN-LAST:event_jButton3ActionPerformed
                                                
    catch(Exception e){ 
    }
        }
        pname1.setText("  ");
        ubprice.setText("  ");
        uprice.setText("  ");
        sqty.setText("   ");
        
        
        
    }
        
        
  
        
        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        String name = jTextField4.getText();
         
        String sql = "Select unit, product_name, unit_price, ub_price,quantity,profit from addsave1 where product_name LIKE '%"+ name +"%'";
        try{
        
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
      
      
        
         
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
       
    
            
        
    
    }//GEN-LAST:event_jTable1KeyPressed

    private void pname1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pname1KeyPressed
        int key =evt.getKeyCode();
        if(key==10){
            
         ubprice.requestFocus();
         
            
        }
    }//GEN-LAST:event_pname1KeyPressed

    private void upriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upriceKeyPressed
        
         int key =evt.getKeyCode();
        if(key==10){
            
         sqty.requestFocus();
         
            
        }
        
    }//GEN-LAST:event_upriceKeyPressed

    private void pname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pname1ActionPerformed

    private void ubpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubpriceKeyPressed
        // TODO add your handling code here:
        int key =evt.getKeyCode();
        if(key==10){
            
         uprice.requestFocus();
        
    }//GEN-LAST:event_ubpriceKeyPressed
     
    }
        
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField pname1;
    private javax.swing.JTextField sqty;
    private javax.swing.JTextField ubprice;
    private javax.swing.JTextField uprice;
    // End of variables declaration//GEN-END:variables

   
    }

