/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mycode.dbconnect;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author Acer
 */
public class arrears extends javax.swing.JPanel {

    /**
     * Creates new form arrears
     */
    public arrears() {
        initComponents();
         jPanel1.setBackground(new Color(255,255,255,220));
       
          jTable1.getTableHeader().setFont(new Font("Segoe UI",Font.BOLD,24));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(157,136,203));
        jTable1.getTableHeader().setForeground( Color.BLACK);
        jTable1.setRowHeight(35);
        data_load();
    }
    Connection con;
    PreparedStatement pst;
    
    
     public void data_load(){
        
       try{
           
          Statement s = dbconnect.connect().createStatement(); 
          ResultSet rs = s.executeQuery("SELECT * FROM coustomer");
          Vector v = new Vector();
          while(rs.next()){
              
            v.add(rs.getString("cus_name"));
            
            DefaultComboBoxModel com = new DefaultComboBoxModel(v);
            jComboBox1.setModel(com);
              
              
          }
          
           
           
           
       } catch(Exception e){
           
       }   
       
     }
 
    public void date(){
    
         
         SimpleDateFormat df1 = new SimpleDateFormat("yyyy-MM-dd");
     String fdate = df1.format(jDateChooser1.getDate());
     
     SimpleDateFormat df2 = new SimpleDateFormat("yyyy-MM-dd");
     String tdate = df2.format(jDateChooser2.getDate());
     String name1 =jComboBox1.getSelectedItem().toString();
             
     try{
            
           DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();
           dt.setRowCount(0);
           Statement  s = dbconnect.connect().createStatement();
           ResultSet rs=s.executeQuery("SELECT * FROM sales WHERE name = '"+name1+"' AND date_s BETWEEN  '"+fdate+"' AND '"+tdate+"' AND status NOT IN ('Paid')  ");
            
           while(rs.next()){
               
             Vector v = new Vector();  
              v.add(rs.getString(9));
              v.add(rs.getString(2));
              v.add(rs.getString(4));
              v.add(rs.getString(10));
              v.add(rs.getString(5));
              v.add(rs.getString(7));
              
              dt.addRow(v);
           }
            
        }catch(SQLException e){
            
           System.out.println(e);
            
        }
         
         
         
         
     }
    
    public void cart_total(){
        
        int numofrow = jTable1.getRowCount();
        
        
        double total = 0;
        
        for(int i =0 ; i<numofrow;i++){
            
           
           double value = Double.valueOf(jTable1.getValueAt(i,3).toString());
           total+=value;
           
        }
        String tot=String.format("%.2f", total); 
      // jLabel6.setText(Double.toString(tot));
       jLabel6.setText(tot);
        
        

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1917, 848));
        setPreferredSize(new java.awt.Dimension(1917, 848));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(0, 255, 204));
        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("00.00");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 770, 180, 40));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Acer\\Documents\\NetBeansProjects\\bill\\src\\main\\Search.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 495, 60, 50));

        jDateChooser1.setForeground(new java.awt.Color(51, 102, 255));
        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 290, 44));

        jDateChooser2.setForeground(new java.awt.Color(255, 51, 204));
        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jDateChooser2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 290, 44));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 67, 396, 44));

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setText("name  :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 67, 84, 44));

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setText("from  :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 44));

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setText("to       :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, 44));

        jTable1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Invoice ID", "Bill Total", "Arrears", "Status", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 1330, 850));

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setText("arrears  :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 770, 110, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 850));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Untitled5.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
     date();
     cart_total();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
